run:
  timeout: 5m

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-use-default: false
  exclude-rules:
    - path: ".*\\.pb\\.go$"
      linters:
        - errcheck
        - govet
        - ineffassign
        - staticcheck
        - unused
    - path: ".*_generate\\.go$"
      linters:
        - errcheck
        - govet
        - ineffassign
        - staticcheck
        - unused

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
