apiVersion: batch/v1
kind: CronJob
metadata:
  labels:
    app.kubernetes.io/name: sealos-nm-cleanup
    app.kubernetes.io/part-of: sealos-nm
  name: sealos-nm-cleanup
  namespace: sealos-nm-system
spec:
  schedule: "0 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 3
      template:
        metadata:
          labels:
            app.kubernetes.io/name: sealos-nm-cleanup
            app.kubernetes.io/part-of: sealos-nm
        spec:
          restartPolicy: OnFailure
          containers:
          - image: docker.io/dinoallo/sealos-nm-agent:dev
            imagePullPolicy: IfNotPresent
            name: sealos-nm-cleanup
            command:
            - /app/cleanup
            resources:
              limits:
                cpu: 500m
                memory: 256Mi
              requests:
                cpu: 100m
                memory: 64Mi
            env:
            - name: DB_ENABLED
              value: "true"
            - name: DB_URI
              valueFrom:
                secretKeyRef:
                  key: db_uri
                  name: nm-db-conn-credential
                  optional: false
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  key: db_name
                  name: nm-db-conn-credential
                  optional: false
            envFrom:
            - configMapRef:
                name: agent-env
