apiVersion: v1
kind: Pod
metadata:
  name: sealos-nm-agent-test
  namespace: sealos-nm-system
  labels:
    app.kubernetes.io/name: sealos-nm-agent-test
    app.kubernetes.io/part-of: sealos-nm
    k8s-app: sealos-nm-agent-test
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchLabels:
            k8s-app: cilium
        topologyKey: kubernetes.io/hostname
  tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule
  restartPolicy: Never
  containers:
  - image: docker.io/dinoallo/sealos-nm-agent-test:dev
    imagePullPolicy: IfNotPresent
    name: sealos-nm-agent-test
    ports:
    - containerPort: 5005
      hostPort: 5005
      name: agent-grpc
      protocol: TCP
    resources:
      requests:
        cpu: 250m
        memory: 64Mi
    env:
    - name: DB_URI
      valueFrom:
        secretKeyRef:
          key: db_uri
          name: nm-db-conn-credential
          optional: false
    securityContext:
      capabilities:
        add:
        - IPC_LOCK
        - SYS_ADMIN
        - SYS_RESOURCE
        - DAC_OVERRIDE
        - FOWNER
        drop:
        - ALL
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
    volumeMounts:
    - mountPath: /sys/fs/bpf
      mountPropagation: HostToContainer
      name: bpf-maps
    - mountPath: /etc/sealos-nm-agent/config
      readOnly: true
      name: config
  dnsPolicy: ClusterFirstWithHostNet
  hostNetwork: true
  volumes:
  - name: bpf-maps
    hostPath:
      path: /sys/fs/bpf
      type: Directory
  - name: config
    configMap:
      name: config
