apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    sealos-db-provider-cr: <name-placeholder>
    app.kubernetes.io/instance: <name-placeholder>
    app.kubernetes.io/managed-by: kbcli
  name: <name-placeholder>
  namespace: <namespace-placeholder>
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    sealos-db-provider-cr: <name-placeholder>
    app.kubernetes.io/instance: <name-placeholder>
    app.kubernetes.io/managed-by: kbcli
  name: <name-placeholder>
  namespace: <namespace-placeholder>
rules:
  - apiGroups:
      - '*'
    resources:
      - '*'
    verbs:
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    sealos-db-provider-cr: <name-placeholder>
    app.kubernetes.io/instance: <name-placeholder>
    app.kubernetes.io/managed-by: kbcli
  name: <name-placeholder>
  namespace: <namespace-placeholder>
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: <name-placeholder>
subjects:
  - kind: ServiceAccount
    name: <name-placeholder>
---
apiVersion: apps.kubeblocks.io/v1alpha1
kind: Cluster
metadata:
  finalizers:
    - cluster.kubeblocks.io/finalizer
  labels:
    clusterdefinition.kubeblocks.io/name: mongodb
    clusterversion.kubeblocks.io/name: <mongodb-version-placeholder>
    sealos-db-provider-cr: <name-placeholder>
  annotations: {}
  name: <name-placeholder>
  namespace: <namespace-placeholder>
spec:
  affinity:
    nodeLabels: {}
    podAntiAffinity: Preferred
    tenancy: SharedNode
    topologyKeys:
      - kubernetes.io/hostname
  clusterDefinitionRef: mongodb
  clusterVersionRef: <mongodb-version-placeholder>
  componentSpecs:
    - componentDefRef: mongodb
      monitor: true
      name: mongodb
      replicas: <replica-placeholder>
      resources:
        limits:
          cpu: 3000m
          memory: 8192Mi
        requests:
          cpu: 300m
          memory: 819Mi
      serviceAccountName: <name-placeholder>
      volumeClaimTemplates:
        - name: data
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 9Gi
  terminationPolicy: Delete
  tolerations: []
