apiVersion: v1
data:
  config.yml: |
    persistent_storage:
      db_name: "sealos-networkmanager"
      connection_timeout: 5
      max_pool_size: 100
      expire_after: 1800
    traffic_record_store:
      max_worker_count: 2
      max_recver_count: 2
      monitor_sync_period: 60
      max_monitor_entries_size: 1048576
      max_record_to_flush: 32768
      max_report_queue_len: 1048576
      max_record_queue_len: 1048576
      max_record_waiting_time: 60
      traffic_record_coll: "traffic_records"
    cilium_endpoint_store:
      max_worker_count: 2
      partial_ttl_index: "stale"
      endpoint_sync_period: 10
      max_endpoint_entries_size: 100
      cilium_endpoint_coll: "cilium_endpoints"
    bytecount_factory:
      perf_buffer_size: 65536
      max_reader_count: 2
      max_processor_count: 3
      max_traffic_queue_len: 1024
    traffic_service:
      max_connection_idle: 15
      port: 65505
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: agent
  name: sealos-nm-agent-config
  namespace: sealos-nm-system
---
apiVersion: v1
data:
  db_uri: <database-connection-string>
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: agent
  name: sealos-nm-agent-secret
  namespace: sealos-nm-system
type: Opaque
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name: agent
  name: sealos-nm-agent-daemon
  namespace: sealos-nm-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: agent
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchLabels:
                k8s-app: cilium
            topologyKey: kubernetes.io/hostname
      containers:
      - env:
        - name: DB_URI
          valueFrom:
            secretKeyRef:
              key: db_uri
              name: sealos-nm-agent-secret
              optional: false
        image: 192.168.3.2:5000/dinoallo/sealos-nm-agent:fce7ea9
        imagePullPolicy: IfNotPresent
        name: agent-daemon
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 64Mi
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
            - SYS_ADMIN
            - SYS_RESOURCE
            - DAC_OVERRIDE
            - FOWNER
            drop:
            - ALL
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: FallbackToLogsOnError
        volumeMounts:
        - mountPath: /sys/fs/bpf
          mountPropagation: HostToContainer
          name: bpf-maps
        - mountPath: /etc/sealos-nm-agent/config
          name: config
          readOnly: true
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      volumes:
      - hostPath:
          path: /sys/fs/bpf
          type: Directory
        name: bpf-maps
      - configMap:
          name: sealos-nm-agent-config
        name: config
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 50%
    type: RollingUpdate
