// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64

package traffic

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadTraffic returns the embedded CollectionSpec for traffic.
func loadTraffic() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TrafficBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load traffic: %w", err)
	}

	return spec, err
}

// loadTrafficObjects loads traffic and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*trafficObjects
//	*trafficPrograms
//	*trafficMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTrafficObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadTraffic()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// trafficSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type trafficSpecs struct {
	trafficProgramSpecs
	trafficMapSpecs
}

// trafficSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type trafficProgramSpecs struct {
	SealosFromContainer *ebpf.ProgramSpec `ebpf:"sealos_from_container"`
	SealosToNetdev      *ebpf.ProgramSpec `ebpf:"sealos_to_netdev"`
}

// trafficMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type trafficMapSpecs struct {
	FromContainerTrafficEvents *ebpf.MapSpec `ebpf:"from_container_traffic_events"`
	FromContainerTrafficNotis  *ebpf.MapSpec `ebpf:"from_container_traffic_notis"`
	ToNetdevTrafficEvents      *ebpf.MapSpec `ebpf:"to_netdev_traffic_events"`
	ToNetdevTrafficNotis       *ebpf.MapSpec `ebpf:"to_netdev_traffic_notis"`
}

// trafficObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTrafficObjects or ebpf.CollectionSpec.LoadAndAssign.
type trafficObjects struct {
	trafficPrograms
	trafficMaps
}

func (o *trafficObjects) Close() error {
	return _TrafficClose(
		&o.trafficPrograms,
		&o.trafficMaps,
	)
}

// trafficMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTrafficObjects or ebpf.CollectionSpec.LoadAndAssign.
type trafficMaps struct {
	FromContainerTrafficEvents *ebpf.Map `ebpf:"from_container_traffic_events"`
	FromContainerTrafficNotis  *ebpf.Map `ebpf:"from_container_traffic_notis"`
	ToNetdevTrafficEvents      *ebpf.Map `ebpf:"to_netdev_traffic_events"`
	ToNetdevTrafficNotis       *ebpf.Map `ebpf:"to_netdev_traffic_notis"`
}

func (m *trafficMaps) Close() error {
	return _TrafficClose(
		m.FromContainerTrafficEvents,
		m.FromContainerTrafficNotis,
		m.ToNetdevTrafficEvents,
		m.ToNetdevTrafficNotis,
	)
}

// trafficPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTrafficObjects or ebpf.CollectionSpec.LoadAndAssign.
type trafficPrograms struct {
	SealosFromContainer *ebpf.Program `ebpf:"sealos_from_container"`
	SealosToNetdev      *ebpf.Program `ebpf:"sealos_to_netdev"`
}

func (p *trafficPrograms) Close() error {
	return _TrafficClose(
		p.SealosFromContainer,
		p.SealosToNetdev,
	)
}

func _TrafficClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed traffic_bpfel.o
var _TrafficBytes []byte
