name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_NAME: dinoallo/sealos-nm-agent
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from go.mod
        id: version
        run: |
          VERSION=$(grep -Eo 'v[0-9]+\.[0-9]+\.[0-9]+' go.mod | head -n1)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: build/docker/main/Dockerfile
          platforms: linux/amd64 # Only support amd64 for now
          push: true
          tags: |
            ghcr.io/${{ env.IMAGE_NAME }}:${{ steps.version.outputs.version }}
            ghcr.io/${{ env.IMAGE_NAME }}:latest